version: "3.8"

services:
  dagster-webserver:
    build: .
    container_name: dagster-webserver
    ports:
      - "3000:3000"
    environment:
      - DAGSTER_HOME=/opt/dagster/dagster_home
      - DAGSTER_POSTGRES_USER=${DAGSTER_POSTGRES_USER}
      - DAGSTER_POSTGRES_PASSWORD=${DAGSTER_POSTGRES_PASSWORD}
      - DAGSTER_POSTGRES_HOST=${DAGSTER_POSTGRES_HOST}
      - DAGSTER_POSTGRES_DB=${DAGSTER_POSTGRES_DB}
    networks:
      - coolify
    restart: always

  dagster-daemon:
    build: .
    container_name: dagster-daemon
    command: dagster-daemon run -w workspace.yaml
    environment:
      - DAGSTER_HOME=/opt/dagster/dagster_home
      - DAGSTER_POSTGRES_USER=${DAGSTER_POSTGRES_USER}
      - DAGSTER_POSTGRES_PASSWORD=${DAGSTER_POSTGRES_PASSWORD}
      - DAGSTER_POSTGRES_HOST=${DAGSTER_POSTGRES_HOST}
      - DAGSTER_POSTGRES_DB=${DAGSTER_POSTGRES_DB}
    networks:
      - coolify
    restart: always
    depends_on:
      - dagster-webserver

networks:
  coolify:
    external: true
    name: coolify